
- category: Web Apps
  # description: |
  #   Write a single markdown file and create output in a variety of formats.
  tiles:
    - title: Hyper-IgE syndrome scoring
      href: https://bsolomon.us/app/hies-score/
      thumbnail: img/apps/hies-score.png
      
    - title: Pediatric blood pressure percentiles
      href: https://bsolomon.us/app/pediatric-bp/
      thumbnail: img/pediatric-bp.png

    - title: Invitae genetic testing comparison
      href: https://bsolomon.us/app/invitae-compare/
      thumbnail: img/apps/invitae-compare.png
      
    - title: Santa Clara county pollen trends
      href: https://www.bsolomon.us/app/pollen_count/
      thumbnail: img/apps/pollen-count.png
      
    - title: Kawasaki disease discharge risk
      href: https://www.bsolomon.us/app/pollen_count/
      thumbnail: img/apps/kawasaki-dc.png
      